# -*- coding: utf-8 -*-
"""Assignment1:Weather_Data_Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ufrgoeTHBVP5EMCpPIOPujUAuoURQoDE
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
sns.set(color_codes=True)

# THis function load weather data CSV File in Weather
def readdata(path):
 weather = pd.read_csv(path)
 return weather

# VisualizaHead Function Show first Five Row of Data Instances from CSV to
# Visualize it.
def visualize_head(weather):
  weather.head()

# THis Function Show All Parameters/ Columns of Weather
def parameter_info(weather):
  weather.info()

# In this function Multiple Line plots between Weather Type with air_index and
# Humditity 
#  We can see clearly Weather Condition and effect on Air Index as well Humditity
# Value 
def line_plot(weather):
  # Plotting a figure of width 10 and height 5
  fig = plt.figure()

  fig.set_figheight(5)
  fig.set_figwidth(10)
  weather_type=weather['weather_type'].astype(str)
  air_index=weather['air_pollution_index'].astype(np.float32)
  humidity=weather['humidity'].astype(np.float32)
  plt.plot(weather_type,air_index,label='Air Index')
  plt.plot(weather_type,humidity,label='humidity')
  plt.xlabel('Weather Type')
  plt.ylabel('Air Index and Humidity')
  plt.legend()
  plt.title('Weather Parameters Comparsion')
  plt.show()

# Bar Plot is used to  better visualize data between Weather type and coresponding
# Parameters to check effect of weather on Air index and Humidity Level  
# As  we can see in HAZE weather Air index is Low along with Low Humidity
def bar_plot(weather):
  # Plotting a figure of width 10 and height 5
  fig = plt.figure()
  
  fig.set_figheight(5)
  fig.set_figwidth(10)
  weather_type=weather['weather_type'].astype(str)
  air_index=weather['air_pollution_index'].astype(np.float32)
  humidity=weather['humidity'].astype(np.float32)
  plt.bar(weather_type,air_index,label='Air Index')
  plt.bar(weather_type,humidity,label='humidity')
  plt.xlabel('Weather Type')
  plt.ylabel('Air Index and Humidity')
  plt.legend()
  plt.title('Weather Parameters Comparsion')
  plt.show()

# Scatter Plot is used because it will show more detail for each level of data 
# and i ploted  between Weather type and coresponding
# Parameters  weather on Air index and Humidity Level because these two parameter
  # Effected More On Weather Change 

def scatter_plot(weather):
  # Plotting a figure of width 10 and height 5
  fig = plt.figure()
  
  fig.set_figheight(5)
  fig.set_figwidth(10)
  weather_type=weather['weather_type'].astype(str)
  air_index=weather['air_pollution_index'].astype(np.float32)
  humidity=weather['humidity'].astype(np.float32)
  plt.scatter(weather_type,air_index,label='Air Index')
  plt.scatter(weather_type,humidity,label='humidity')
  plt.xlabel('Weather Type')
  plt.ylabel('Air Index and Humidity')
  plt.legend()
  plt.title('Weather Parameters Comparsion')
  plt.show()

weather=readdata('./weatherdata.csv') #passing path of CSV to readdata function to read CSV file
visualize_head(weather)  # Calling Function for Showing head of data (First 5 rows) 
parameter_info(weather)  # calling function to see columns(Features) of Dataset
line_plot(weather)       # Calling For Line Plot using pyplot
bar_plot(weather)        # Calling For Bar Plot using pyplot
scatter_plot(weather)    # Calling For Scatter Plot using pyplot